In [1]:
#We can find the size and the shape of the array
#size denotes the total number of elements in the array
#shape denotes the number of rows and columns
import numpy as np
a=np.array([1,2,3])
print(a.size)


3


In [6]:
#Finding the shape of array
a=np.array([1,2,3])
print(a.shape)
b=np.array([(1,2),(3,4),(5,6),(7,8)])
print(b.shape)

(3,)
(4, 2)


In [12]:
#reshaping the array
#keep in mind the number of elements in the array while reshaping
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)
a=a.reshape(4,2)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
#printing equispaced value between any two numbers
a=np.linspace(2,10,5)
print(a)

[ 2.  4.  6.  8. 10.]


In [20]:
#max and min element in the array
a=np.array([(1,2,3,4)])
print(a.max())
print(a.min())

4
1


In [22]:
#sum
#axis=0 for rows 
#axis=1 for columns
a=np.array([(1,2,3),(4,5,6)])
print(a.sum(axis=1))

[ 6 15]


In [23]:
#basic math operation
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#x= [[1,2]
#    [3,4]]
#y= [[5,6]
#    [7,8]]

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print (x + y)
print (np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print (x - y)
print (np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print (x * y)
print (np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
